# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53f81380d90d7e0161756117c1e16f1562f5dc5b62d92b513a92d48a8c9d1232d4fc7529ff272be658ac53a5d0d72eb41e1f302ac4bd2e6aabb87e4f877d6a16

test:
  secret_key_base: b1d712da32b6deacd4faaa32588e9d873cbf201fc444d0124a99cbc883566e54f18cddcb5d208af7d5ff358b53eded61e3c39ca65c0a427220f48def4074c7d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
